export const ON_REQUEST_GITHUB_USER_DATA = 'ON_REQUEST_GITHUB_USER_DATA';
export const ON_RESPONSE_GITHUB_USER_DATA = 'ON_RESPONSE_GITHUB_USER_DATA';
export const ON_RESPONSE_ERROR_GITHUB_USER_DATA = 'ON_RESPONSE_ERROR_GITHUB_USER_DATA';